project:
  type: website
  output-dir: docs
  resources:
    - cv_lucas_henriksson.pdf
    - assets/fonts/libertinus/

website:
  title: "Lucas Henriksson"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    grid:
      sidebar-width: 100px
      body-width: 1150px
      margin-width: 100px
