project:
  type: website
  output-dir: docs
  resources:
    - cv_lucas_henriksson.pdf

website:
  title: "Lucas Henriksson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV

format:
  html:
    theme: litera
    toc: false
