---
title: "Lucas Henriksson"
format: html
---

Hi! 

I'm Lucas Henriksson, a PhD student at the [Stockholm School of Economics](https://www.hhs.se/). I am also an affiliated researcher at the [Research Group for Socioeconomic Studies of Technology](https://soetech.org/) at Lund University.

Feel free to reach out via email at [lucas.henriksson\@hhs.se](mailto:lucas.henriksson@hhs.se).

## Research

My research interests are primarily in labor and public economics. Specifically, I'm interested in understanding how social security systems and taxations shape individual choices using applied microeconomic methods. Currently, I am mostly working on ideas related to unemployment insurance in Sweden.

## Policy Reports

### Den svenska välfärden möter den moderna världen – Klarar kommuner och regioner att finansiera välfärden i en global och digital ekonomi?
*Coauthored with [Åsa Hansson](https://portal.research.lu.se/sv/persons/%C3%A5sa-hansson). \[[Published by Ratio in 2025](https://cms.ratio.se/app/uploads/2025/04/rapport-35-den-svenska-valfarden-1.pdf)\]*

*Summary in English*: We analyzes the long-term sustainability of Sweden’s decentralized welfare model under growing fiscal pressure from demographic change, digitalization, and increased labor mobility. We examine the capacity of municipalities and regions to finance welfare services under a tax system dominated by local taxation of labor income. The report identifies structural weaknesses in the current financing model, including a shrinking and uneven local tax base, vertical tax externalities due to overlapping tax powers, and rising mobility of high-income earners. We discuss alternative financing models and propose policy options such as introducing local property taxation, assigning new tax bases like natural resources to local governments, and reducing reliance on labor-based taxation to improve efficiency, equity, and long-term fiscal stability.

## Pre-PhD Publications

### European Tobacco Taxation and Youth Smoking

*Coauthored with [Ida Haggren](https://www.linkedin.com/in/ida-haggren-09782a164/?originalSubdomain=se). \[[Latest version: May 2023](https://drive.google.com/file/d/1kAgsYGCOb98e002SIqiUQ8DpCstIR6fV/view?usp=sharing)\]*

This was (one of) our master's theses, which was awarded the [2023 Scholarship for Student Thesis of the Year by the Institute for Health Economics (IHE) and the Bengt Jönsson Foundation for Health Economic Research.](https://ihe.se/event-kurser/stipendium/2023-2/).


