---
title: "Research"
format:
  html:
    toc: false
---

::: columns

::: {.column width="30%"}
{{< include _sidebar.qmd >}}
:::

::: {.column width="70%"}

<h1>Research</h1>

## Work in Progress

**Union and Insurance Company? How Union-provided Unemployment Insurance affects Unionization Decisions**

Studies how unions' self-funded provision of unemployment insurance affects the recruitment of members. Specifically, I am investigating whether this explains the large and increasing gap in unionization rates between blue-collar and white-collar workers in Sweden.

## Policy Reports

### Den svenska välfärden möter den moderna världen – Klarar kommuner och regioner att finansiera välfärden i en global och digital ekonomi?

*Coauthored with [Åsa Hansson](https://portal.research.lu.se/sv/persons/%C3%A5sa-hansson). \[[Published by Ratio in 2025](https://cms.ratio.se/app/uploads/2025/04/rapport-35-den-svenska-valfarden-1.pdf)\]*

*Summary in English*: We analyzes the long-term sustainability of Sweden’s decentralized welfare model under growing fiscal pressure from demographic change, digitalization, and increased labor mobility. We examine the capacity of municipalities and regions to finance welfare services under a tax system dominated by local taxation of labor income. The report identifies structural weaknesses in the current financing model, including a shrinking and uneven local tax base, vertical tax externalities due to overlapping tax powers, and rising mobility of high-income earners. We discuss reforms to improve efficiency and long-term fiscal stability of the financing of local governments.

### Vem ska finansiera Skånes framtida offentliga välfärd?

*Coauthored with [Åsa Hansson](https://portal.research.lu.se/sv/persons/%C3%A5sa-hansson). \[[Published in KEFU 2026:3](https://portal.research.lu.se/sv/publications/vem-ska-finansiera-sk%C3%A5nes-framtida-offentliga-v%C3%A4lf%C3%A4rd/)\]*

*Summary in English*: We analyze how Skåne's future public welfare can be financed under increasing demographic pressure, mobility, and tax-base challenges. The report discusses alternative tax bases and systems that could increase the set of tools avaiable to local governments to finance welfare services.

:::

:::
